export const History = {
  Games: [
    {
      Player1: "M",
      Player2: "F",
      isLegit: "L",
      LocalEscudo: "/images/Liverpool.png",
      LocalNombre: "LIVERPOOL",
      LocalSlug: "LIVERPOOL",
      LocalResultado: 2,
      VisitanteEscudo: "/images/ParisSaintGermain.png",
      VisitanteNombre: "PARIS SAINT GERMAIN",
      VisitanteSlug: "PSG",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/Barcelona.webp",
      LocalNombre: "BARCELONA",
      LocalSlug: "BARCELONA",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Liverpool.png",
      VisitanteNombre: "LIVERPOOL",
      VisitanteSlug: "LIVERPOOL",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "F",
      isLegit: "L",
      LocalEscudo: "/images/evertonfc.png",
      LocalNombre: "EVERTON",
      LocalSlug: "EVERTON",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Internazionale.png",
      VisitanteNombre: "INTER",
      VisitanteSlug: "INTER",
      VisitanteResultado: 2,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/mancity.png",
      LocalNombre: "MANCHESTER CITY",
      LocalSlug: "MAN CITY",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Internazionale.png",
      VisitanteNombre: "INTER",
      VisitanteSlug: "INTER",
      VisitanteResultado: 3,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 0,
      VisitanteEscudo: "/images/BorussiaDortmund.png",
      VisitanteNombre: "BORUSSIA DORTMUND",
      VisitanteSlug: "DORTMUND",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/bayern04.png",
      LocalNombre: "BAYERN 04 LEVERKUSEN",
      LocalSlug: "BAYERN 04",
      LocalResultado: 0,
      VisitanteEscudo: "/images/Barcelona.webp",
      VisitanteNombre: "BARCELONA",
      VisitanteSlug: "BARCELONA",
      VisitanteResultado: 2,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalSlug: "BAYERN",
      LocalResultado: 0,
      VisitanteEscudo: "/images/mancity.png",
      VisitanteNombre: "MANCHESTER CITY",
      VisitanteSlug: "MAN CITY",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/oporto.png",
      LocalNombre: "PORTO",
      LocalSlug: "PORTO",
      LocalResultado: 0,
      VisitanteEscudo: "/images/arsenalfc.png",
      VisitanteNombre: "ARSENAL",
      VisitanteSlug: "ARSENAL",
      VisitanteResultado: 2,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalSlug: "BAYERN",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteSlug: "CHELSEA",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 1,
      VisitanteEscudo: "/images/AtleticoMadrid.png",
      VisitanteNombre: "ATLETICO MADRID",
      VisitanteSlug: "ATL MADRID",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalSlug: "BAYERN",
      LocalResultado: 2,
      LocalPenalty: 4,
      VisitanteEscudo: "/images/RealMadrid.png",
      VisitanteNombre: "REAL MADRID",
      VisitanteSlug: "REAL MADRID",
      VisitanteResultado: 2,
      VisitantePenalty: 3,
      Penalty: true,
    },
    {
      Player1: "G",
      Player2: "F",
      isLegit: "NO",
      LocalEscudo: "/images/RealMadrid.png",
      LocalNombre: "REAL MADRID",
      LocalSlug: "REAL MADRID",
      LocalResultado: 0,
      VisitanteEscudo: "/images/bayern04.png",
      VisitanteNombre: "BAYERN 04 LEVERKUSEN",
      VisitanteSlug: "BAYERN 04",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 1,
      VisitanteEscudo: "/images/sevillaa.png",
      VisitanteNombre: "SEVILLA",
      VisitanteSlug: "SEVILLA",
      VisitanteResultado: 2,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/Chelsea.png",
      LocalNombre: "CHELSEA",
      LocalSlug: "CHELSEA",
      LocalResultado: 2,
      VisitanteEscudo: "/images/BayernMunchen.png",
      VisitanteNombre: "BAYERN MUNICH",
      VisitanteSlug: "BAYERN",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/BorussiaDortmund.png",
      LocalNombre: "BORUSSIA DORTMUND",
      LocalSlug: "DORTMUND",
      LocalResultado: 1,
      LocalPenalty: 6,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteSlug: "CHELSEA",
      VisitanteResultado: 1,
      VisitantePenalty: 7,
      Penalty: true,
    },
    {
      Player1: "G",
      Player2: "F",
      isLegit: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalSlug: "MAN UNITED",
      LocalResultado: 0,
      VisitanteEscudo: "/images/ParisSaintGermain.png",
      VisitanteNombre: "PARIS SAINT GERMAIN",
      VisitanteSlug: "PSG",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "NO",
      LocalEscudo: "/images/oporto.png",
      LocalNombre: "PORTO",
      LocalSlug: "PORTO",
      LocalResultado: 1,
      VisitanteEscudo: "/images/BayernMunchen.png",
      VisitanteNombre: "BAYERN MUNICH",
      VisitanteSlug: "BAYERN",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "F",
      isLegit: "NO",
      LocalEscudo: "/images/newcastlee.png",
      LocalNombre: "NEWCASTLE",
      LocalSlug: "NEWCASTLE",
      LocalResultado: 3,
      VisitanteEscudo: "/images/valenciafc.png",
      VisitanteNombre: "VALENCIA",
      VisitanteSlug: "VALENCIA",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "F",
      isLegit: "L",
      LocalEscudo: "/images/Tottenham.png",
      LocalNombre: "TOTTENHAM",
      LocalSlug: "TOTTENHAM",
      LocalResultado: 2,
      VisitanteEscudo: "/images/arsenalfc.png",
      VisitanteNombre: "ARSENAL",
      VisitanteSlug: "ARSENAL",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/RealMadrid.png",
      LocalNombre: "REAL MADRID",
      LocalSlug: "REAL MADRID",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Tottenham.png",
      VisitanteNombre: "TOTTENHAM",
      VisitanteSlug: "TOTTENHAM",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "F",
      isLegit: "L",
      LocalEscudo: "/images/Chelsea.png",
      LocalNombre: "CHELSEA",
      LocalSlug: "CHELSEA",
      LocalResultado: 2,
      LocalPenalty: 4,
      VisitanteEscudo: "/images/Barcelona.webp",
      VisitanteNombre: "BARCELONA",
      VisitanteSlug: "BARCELONA",
      VisitanteResultado: 2,
      VisitantePenalty: 5,
      Penalty: true,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/oporto.png",
      LocalNombre: "PORTO",
      LocalSlug: "PORTO",
      LocalResultado: 0,
      VisitanteEscudo: "/images/mancity.png",
      VisitanteNombre: "MANCHESTER CITY",
      VisitanteSlug: "MAN CITY",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "M",
      Player2: "F",
      isLegit: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalSlug: "MAN UNITED",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Liverpool.png",
      VisitanteNombre: "LIVERPOOL",
      VisitanteSlug: "LIVERPOOL",
      VisitanteResultado: 0,
      Penalty: false,
    },

    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/Ajax.png",
      LocalNombre: "AJAX",
      LocalSlug: "AJAX",
      LocalResultado: 3,
      VisitanteEscudo: "/images/arsenalfc.png",
      VisitanteNombre: "ARSENAL",
      VisitanteSlug: "ARSENAL",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalSlug: "MAN UNITED",
      LocalResultado: 1,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteSlug: "JUVENTUS",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/newcastlee.png",
      LocalNombre: "NEWCASTLE",
      LocalSlug: "NEWCASTLE",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Zenit.png",
      VisitanteNombre: "ZENIT",
      VisitanteSlug: "ZENIT",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/Liverpool.png",
      LocalNombre: "LIVERPOOL",
      LocalSlug: "LIVERPOOL",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Tottenham.png",
      VisitanteNombre: "TOTTENHAM",
      VisitanteSlug: "TOTTENHAM",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "NO",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 0,
      VisitanteEscudo: "/images/villar.png",
      VisitanteNombre: "VILLA REAL",
      VisitanteSlug: "VILLA REAL",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalSlug: "BAYERN",
      LocalResultado: 2,
      LocalPenalty: 3,
      VisitanteEscudo: "/images/RealMadrid.png",
      VisitanteNombre: "REAL MADRID",
      VisitanteSlug: "REAL MADRID",
      VisitanteResultado: 2,
      VisitantePenalty: 5,
      Penalty: true,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalSlug: "BAYERN",
      LocalResultado: 1,
      VisitanteEscudo: "/images/RealMadrid.png",
      VisitanteNombre: "REAL MADRID",
      VisitanteSlug: "REAL MADRID",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "F",
      isLegit: "L",
      LocalEscudo: "/images/milan_test.png",
      LocalNombre: "AC MILAN",
      LocalSlug: "AC MILAN",
      LocalResultado: 2,
      VisitanteEscudo: "/images/ParisSaintGermain.png",
      VisitanteNombre: "PARIS SAINT GERMAIN",
      VisitanteSlug: "PSG",
      VisitanteResultado: 4,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/Liverpool.png",
      LocalNombre: "LIVERPOOL",
      LocalSlug: "LIVERPOOL",
      LocalResultado: 1,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteSlug: "JUVENTUS",
      VisitanteResultado: 2,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 2,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteSlug: "JUVENTUS",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/arsenalfc.png",
      LocalNombre: "ARSENAL",
      LocalSlug: "ARSENAL",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Internazionale.png",
      VisitanteNombre: "INTER",
      VisitanteSlug: "INTER",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/Barcelona.webp",
      LocalNombre: "BARCELONA",
      LocalSlug: "BARCELONA",
      LocalResultado: 0,
      LocalPenalty: 4,
      VisitanteEscudo: "/images/milan_test.png",
      VisitanteNombre: "AC MILAN",
      VisitanteSlug: "AC MILAN",
      VisitanteResultado: 0,
      VisitantePenalty: 2,
      Penalty: true,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "NO",
      LocalEscudo: "/images/oporto.png",
      LocalNombre: "PORTO",
      LocalSlug: "PORTO",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Liverpool.png",
      VisitanteNombre: "LIVERPOOL",
      VisitanteSlug: "LIVERPOOL",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "NO",
      LocalEscudo: "/images/Internazionale.png",
      LocalNombre: "INTER",
      LocalSlug: "INTER",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Ajax.png",
      VisitanteNombre: "AJAX",
      VisitanteSlug: "AJAX",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/arsenalfc.png",
      LocalNombre: "ARSENAL",
      LocalSlug: "ARSENAL",
      LocalResultado: 0,
      VisitanteEscudo: "/images/valenciafc.png",
      VisitanteNombre: "VALENCIA",
      VisitanteSlug: "VALENCIA",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/sevillaa.png",
      LocalNombre: "SEVILLA",
      LocalSlug: "SEVILLA",
      LocalResultado: 1,
      VisitanteEscudo: "/images/BayernMunchen.png",
      VisitanteNombre: "BAYERN MUNICH",
      VisitanteSlug: "BAYERN",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteSlug: "CHELSEA",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/SSC_Neapel.svg.png",
      LocalNombre: "NAPOLI",
      LocalSlug: "NAPOLI",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Zenit.png",
      VisitanteNombre: "ZENIT",
      VisitanteSlug: "ZENIT",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/Tottenham.png",
      LocalNombre: "TOTTENHAM",
      LocalSlug: "TOTTENHAM",
      LocalResultado: 1,
      VisitanteEscudo: "/images/AstonVilla.png",
      VisitanteNombre: "ASTON VILLA",
      VisitanteSlug: "ASTON VILLA",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/mancity.png",
      LocalNombre: "MANCHESTER CITY",
      LocalSlug: "MAN CITY",
      LocalResultado: 1,
      VisitanteEscudo: "/images/ASRoma.png",
      VisitanteNombre: "ROMA",
      VisitanteSlug: "ROMA",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalSlug: "MAN UNITED",
      LocalResultado: 3,
      VisitanteEscudo: "/images/valenciafc.png",
      VisitanteNombre: "VALENCIA",
      VisitanteSlug: "VALENCIA",
      VisitanteResultado: 2,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 0,
      LocalPenalty: 4,
      VisitanteEscudo: "/images/AstonVilla.png",
      VisitanteNombre: "ASTON VILLA",
      VisitanteSlug: "ASTON VILLA",
      VisitanteResultado: 0,
      VisitantePenalty: 5,
      Penalty: true,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/sevillaa.png",
      LocalNombre: "SEVILLA",
      LocalSlug: "SEVILLA",
      LocalResultado: 1,
      VisitanteEscudo: "/images/mancity.png",
      VisitanteNombre: "MANCHESTER CITY",
      VisitanteSlug: "MAN CITY",
      VisitanteResultado: 2,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 3,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteSlug: "JUVENTUS",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "G",
      isLegit: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalSlug: "BAYERN",
      LocalResultado: 2,
      VisitanteEscudo: "/images/RealMadrid.png",
      VisitanteNombre: "REAL MADRID",
      VisitanteSlug: "REAL MADRID",
      VisitanteResultado: 1,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "M",
      isLegit: "L",
      LocalEscudo: "/images/RealMadrid.png",
      LocalNombre: "REAL MADRID",
      LocalSlug: "REAL MADRID",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Internazionale.png",
      VisitanteNombre: "INTER",
      VisitanteSlug: "INTER",
      VisitanteResultado: 0,
      Penalty: false,
    },
  ],
  best_match: [
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/mancity.png",
      LocalNombre: "MANCHESTER CITY",
      LocalSlug: "MAN CITY",
      LocalResultado: 4,
      VisitanteEscudo: "/images/ManchesterUnited.png",
      VisitanteNombre: "MANCHESTER UNITED",
      VisitanteSlug: "MAN UNITED",
      VisitanteResultado: 3,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/milan_test.png",
      LocalNombre: "AC MILAN",
      LocalSlug: "AC MILAN",
      LocalResultado: 7,
      VisitanteEscudo: "/images/Tottenham.png",
      VisitanteNombre: "TOTTENHAM",
      VisitanteSlug: "TOTTENHAM",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/SportingLisboa.png",
      LocalNombre: "SPORTING",
      LocalSlug: "SPORTING",
      LocalResultado: 5,
      VisitanteEscudo: "/images/SanLorenzo.png",
      VisitanteNombre: "SAN LORENZO",
      VisitanteSlug: "SAN LORENZO",
      VisitanteResultado: 4,
      Penalty: false,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteSlug: "CHELSEA",
      VisitanteResultado: 2,
      Penalty: false,
    },
  ],
  torneos: [
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalSlug: "PSG",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteSlug: "CHELSEA",
      VisitanteResultado: 0,
      Penalty: false,
    },
    {
      Player1: "G",
      Player2: "F",
      Result: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalSlug: "BAYERN",
      LocalResultado: 1,
      VisitanteEscudo: "/images/mancity.png",
      VisitanteNombre: "MANCHESTER CITY",
      VisitanteSlug: "MAN CITY",
      VisitanteResultado: 0,
      Penalty: false,
    },
  ],
};

export const stats_marcos = {
  info: {
    photo_profile: "/images/Marcos.webp",
    background_profile: "/images/chelsea_cover.webp",
    rank_profile: "11",
    shield_profile: "/images/Chelsea.png",
    background_blur_profile: "/images/che_blur.webp",
    photo_blur_profile: "/images/shield_blur.webp",
    name_profile: "Marcos",
    surname_profile: "Aquino",
    team_id: "FC",
    team_profile: "CHELSEA",
    trophies: 2,
  },
  finals: {
    matchs: [
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalSlug: "LIVERPOOL",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalSlug: "LIVERPOOL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Barcelona.webp",
        VisitanteNombre: "BARCELONA",
        VisitanteSlug: "BARCELONA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/evertonfc.png",
        LocalNombre: "EVERTON",
        LocalSlug: "EVERTON",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteSlug: "INTER",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/mancity.png",
        LocalNombre: "MANCHESTER CITY",
        LocalSlug: "MAN CITY",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteSlug: "INTER",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 0,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MANCHESTER CITY",
        VisitanteSlug: "MAN CITY",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalSlug: "PORTO",
        LocalResultado: 0,
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteSlug: "ARSENAL",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/AtleticoMadrid.png",
        LocalNombre: "ATLETICO MADRID",
        LocalSlug: "ATL MADRID",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalSlug: "REAL MADRID",
        LocalResultado: 2,
        LocalPenalty: 3,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 2,
        VisitantePenalty: 4,
        Penalty: true,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 1,
        LocalPenalty: 7,
        VisitanteEscudo: "/images/BorussiaDortmund.png",
        VisitanteNombre: "BORUSSIA DORTMUND",
        VisitanteSlug: "DORTMUND",
        VisitanteResultado: 1,
        VisitantePenalty: 6,
        Penalty: true,
      },
      {
        isLegit: "NO",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 0,
        VisitanteEscudo: "/images/oporto.png",
        VisitanteNombre: "PORTO",
        VisitanteSlug: "PORTO",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalSlug: "TOTTENHAM",
        LocalResultado: 2,
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteSlug: "ARSENAL",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalSlug: "REAL MADRID",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteSlug: "TOTTENHAM",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 2,
        LocalPenalty: 4,
        VisitanteEscudo: "/images/Barcelona.webp",
        VisitanteNombre: "BARCELONA",
        VisitanteSlug: "BARCELONA",
        VisitanteResultado: 2,
        VisitantePenalty: 5,
        Penalty: true,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MANCHESTER UNITED",
        LocalSlug: "MAN UNITED",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteSlug: "LIVERPOOL",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalSlug: "ARSENAL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Ajax.png",
        VisitanteNombre: "AJAX",
        VisitanteSlug: "AJAX",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/Zenit.png",
        LocalNombre: "ZENIT",
        LocalSlug: "ZENIT",
        LocalResultado: 0,
        VisitanteEscudo: "/images/newcastlee.png",
        VisitanteNombre: "NEWCASTLE",
        VisitanteSlug: "NEWCASTLE",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalSlug: "TOTTENHAM",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteSlug: "LIVERPOOL",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "M",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/villar.png",
        LocalNombre: "VILLA REAL",
        LocalSlug: "VILLA REAL",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalSlug: "REAL MADRID",
        LocalResultado: 2,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalSlug: "REAL MADRID",
        LocalResultado: 0,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteSlug: "ARSENAL",
        VisitanteResultado: 3,
        LocalEscudo: "/images/internazionale.png",
        LocalNombre: "INTER",
        LocalSlug: "INTER",
        LocalResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        VisitanteEscudo: "/images/Barcelona.webp",
        VisitanteNombre: "BARCELONA",
        VisitanteSlug: "BARCELONA",
        VisitanteResultado: 0,
        VisitantePenalty: 4,
        LocalEscudo: "/images/milan_test.png",
        LocalNombre: "AC MILAN",
        LocalSlug: "AC MILAN",
        LocalResultado: 0,
        LocalPenalty: 2,
        Penalty: true,
      },
      {
        isLegit: "NO",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteSlug: "LIVERPOOL",
        VisitanteResultado: 2,
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalSlug: "PORTO",
        LocalResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        VisitanteEscudo: "/images/internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteSlug: "INTER",
        VisitanteResultado: 3,
        LocalEscudo: "/images/Ajax.png",
        LocalNombre: "AJAX",
        LocalSlug: "AJAX",
        LocalResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/valenciafc.png",
        LocalNombre: "VALENCIA",
        LocalSlug: "VALENCIA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteSlug: "ARSENAL",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/Zenit.png",
        LocalNombre: "ZENIT",
        LocalSlug: "ZENIT",
        LocalResultado: 0,
        VisitanteEscudo: "/images/SSC_Neapel.svg.png",
        VisitanteNombre: "NAPOLI",
        VisitanteSlug: "NAPOLI",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/AstonVilla.png",
        LocalNombre: "ASTON VILLA",
        LocalSlug: "ASTON VILLA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteSlug: "TOTTENHAM",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/valenciafc.png",
        LocalNombre: "VALENCIA",
        LocalSlug: "VALENCIA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MANCHESTER UNITED",
        VisitanteSlug: "MAN UNITED",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/internazionale.png",
        LocalNombre: "INTER",
        LocalSlug: "INTER",
        LocalResultado: 0,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteSlug: "REAL MADRID",
        VisitanteResultado: 3,
        Penalty: false,
      },
    ],
    stats: {
      win: 10,
      loss: 22,
      porcent: "31%",
    },
  },
  clasics: {
    matchs: [
      {
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Final - Verano",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        Raiz: "16avos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Cuartos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        Raiz: "16avos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        LocalPenalty: 5,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        VisitantePenalty: 4,
        Penalty: true,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        LocalPenalty: 5,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        VisitantePenalty: 4,
        Penalty: true,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Draw",
        Raiz: "Amistoso",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        Raiz: "Fase Grupos - Verano",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        Raiz: "Fase Grupos - Invierno",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Victory",
        Raiz: "Semifinal",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "M",
        Player2: "G",
        Result: "Defeat",
        Raiz: "16Avos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalSlug: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 1,
        Penalty: false,
      },
    ],
    stats: {
      win: 4,
      loss: 10,
      draw: 1,
      porcent: "26%",
    },
  },
};

export const stats_franco = {
  info: {
    photo_profile: "/images/fran.jpg",
    background_profile: "/images/psg_cover.webp",
    rank_profile: "1",
    shield_profile: "/images/ParisSaintGermain.png",
    background_blur_profile: "/images/ps_blur.webp",
    photo_blur_profile: "/images/shield_blur.webp",
    name_profile: "Franco",
    surname_profile: "Chaparro",
    team_id: "PARIS",
    team_profile: "SAINT GERMAIN",
    trophies: 6,
  },
  finals: {
    matchs: [
      {
        isLegit: "L",
        Player1: "F", 
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteSlug: "LIVERPOOL",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Internazionale.png",
        LocalNombre: "INTER",
        LocalSlug: "INTER",
        LocalResultado: 2,
        VisitanteEscudo: "/images/evertonfc.png",
        VisitanteNombre: "EVERTON",
        VisitanteSlug: "EVERTON",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/BorussiaDortmund.png",
        VisitanteNombre: "BORUSSIA DORTMUND",
        VisitanteSlug: "DORTMUND",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/bayern04.png",
        LocalNombre: "BAYERN 04 LEVERKUSEN",
        LocalSlug: "BAYERN 04",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Barcelona.webp",
        VisitanteNombre: "BARCELONA",
        VisitanteSlug: "BARCELONA",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 1,
        VisitanteEscudo: "/images/AtleticoMadrid.png",
        VisitanteNombre: "ATLETICO MADRID",
        VisitanteSlug: "ATL MADRID",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteSlug: "REAL MADRID",
        VisitanteResultado: 2,
        VisitantePenalty: 3,
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 2,
        LocalPenalty: 4,
        Penalty: true,
      },
      {
        isLegit: "NO",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/bayern04.png",
        LocalNombre: "BAYERN 04 LEVERKUSEN",
        LocalSlug: "BAYERN 04",
        LocalResultado: 1,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteSlug: "REAL MADRID",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 1,
        VisitanteEscudo: "/images/sevillaa.png",
        VisitanteNombre: "SEVILLA",
        VisitanteSlug: "SEVILLA",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MANCHESTER UNITED",
        VisitanteSlug: "MAN UNITED",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/valenciafc.png",
        LocalNombre: "VALENCIA",
        LocalSlug: "VALENCIA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/newcastlee.png",
        VisitanteNombre: "NEWCASTLE",
        VisitanteSlug: "NEWCASTLE",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalSlug: "ARSENAL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteSlug: "TOTTENHAM",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Barcelona.webp",
        LocalNombre: "BARCELONA",
        LocalSlug: "BARCELONA",
        LocalResultado: 2,
        LocalPenalty: 5,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 2,
        VisitantePenalty: 4,
        Penalty: true,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalSlug: "PORTO",
        LocalResultado: 0,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MANCHESTER CITY",
        VisitanteSlug: "MAN CITY",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalSlug: "LIVERPOOL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MANCHESTER UNITED",
        VisitanteSlug: "MAN UNITED",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Ajax.png",
        LocalNombre: "AJAX",
        LocalSlug: "AJAX",
        LocalResultado: 3,
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteSlug: "ARSENAL",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MANCHESTER UNITED",
        LocalSlug: "MAN UNITED",
        LocalResultado: 1,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/newcastlee.png",
        LocalNombre: "NEWCLASTLE",
        LocalSlug: "NEWCASTLE",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Zenit.png",
        VisitanteNombre: "ZENIT",
        VisitanteSlug: "ZENIT",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalSlug: "LIVERPOOL",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteSlug: "TOTTENHAM",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "F",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/villar.png",
        VisitanteNombre: "VILLA REAL",
        VisitanteSlug: "VILLA REAL",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 4,
        VisitanteEscudo: "/images/milan_test.png",
        VisitanteNombre: "AC MILAN",
        VisitanteSlug: "AC MILAN",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalSlug: "LIVERPOOL",
        LocalResultado: 1,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Barcelona.webp",
        LocalNombre: "BARCELONA",
        LocalSlug: "BARCELONA",
        LocalResultado: 0,
        LocalPenalty: 4,
        VisitanteEscudo: "/images/milan_test.png",
        VisitanteNombre: "AC MILAN",
        VisitanteSlug: "AC MILAN",
        VisitanteResultado: 0,
        VisitantePenalty: 2,
        Penalty: true,
      },
      {
        isLegit: "NO",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/internazionale.png",
        LocalNombre: "INTER",
        LocalSlug: "INTER",
        LocalResultado: 3,
        VisitanteEscudo: "/images/Ajax.png",
        VisitanteNombre: "AJAX",
        VisitanteSlug: "AJAX",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalSlug: "ARSENAL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/valenciafc.png",
        VisitanteNombre: "VALENCIA",
        VisitanteSlug: "VALENCIA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/sevillaa.png",
        LocalNombre: "SEVILLA",
        LocalSlug: "SEVILLA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalSlug: "TOTTENHAM",
        LocalResultado: 1,
        VisitanteEscudo: "/images/AstonVilla.png",
        VisitanteNombre: "ASTON VILLA",
        VisitanteSlug: "ASTON VILLA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MANCHESTER UNITED",
        LocalSlug: "MAN UNITED",
        LocalResultado: 3,
        VisitanteEscudo: "/images/valenciafc.png",
        VisitanteNombre: "VALENCIA",
        VisitanteSlug: "VALENCIA",
        VisitanteResultado: 2,
        Penalty: false,
      },
  
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 0,
        LocalPenalty: 4,
        VisitanteEscudo: "/images/AstonVilla.png",
        VisitanteNombre: "ASTON VILLA",
        VisitanteSlug: "ASTON VILLA",
        VisitanteResultado: 0,
        VisitantePenalty: 5,
        Penalty: true,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        LocalEscudo: "/images/sevillaa.png",
        LocalNombre: "SEVILLA",
        LocalSlug: "SEVILLA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MANCHESTER CITY",
        VisitanteSlug: "MAN CITY",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 2,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteSlug: "REAL MADRID",
        VisitanteResultado: 1,
        Penalty: false,
      },
    ],
    stats: {
      win: 22,
      loss: 13,
      porcent: "61%",
    },
  },
  clasics: {
    matchs: [
      {
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        Raiz: "Final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        Raiz: "Final - Verano",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        Raiz: "16avos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        Raiz: "Cuartos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "M",
        Result: "Victory",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        Raiz: "Semifinal",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 2,
        LocalPenalty: 5,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 2,
        VisitantePenalty: 4,
        Penalty: true,
      },
      {
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        Raiz: "Final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "G",
        Result: "Victory",
        Raiz: "Cuartos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "G",
        Result: "Draw",
        Raiz: "Fase de grupos - Verano",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "F",
        Player2: "G",
        Result: "Defeat",
        Raiz: "16Avos",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Result: "Victory",
        Raiz: "Octavos de Final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 1,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Result: "Victory",
        Raiz: "Cuartos de Final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalSlug: "PSG",
        LocalResultado: 0,
        LocalPenalty: 5,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteSlug: "JUVENTUS",
        VisitanteResultado: 0,
        VisitantePenalty: 4,
        Penalty: true,
      },
    ],
    stats: {
      porcent: "88%",
      win: 12,
      loss: 2,
    },
  },
};

export const stats_gaston = {
  info: {
    photo_profile: "/images/gaston.jpg",
    background_profile: "/images/juventus_cover.webp",
    rank_profile: "17",
    shield_profile: "/images/da-removebg-preview.png",
    background_blur_profile: "/images/juv_blur.webp",
    photo_blur_profile: "/images/shield_blur.webp",
    name_profile: "Gaston",
    surname_profile: "Chaparro",
    team_id: "FC",
    team_profile: "JUVENTUS",
    trophies: 1,
  },
  finals: {
    matchs: [
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Barcelona.webp",
        LocalNombre: "BARCELONA",
        LocalSlug: "BARCELONA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteSlug: "LIVERPOOL",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/Internazionale.png",
        LocalNombre: "INTER",
        LocalSlug: "INTER",
        LocalResultado: 3,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MANCHESTER CITY",
        VisitanteSlug: "MAN CITY",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/BorussiaDortmund.png",
        LocalNombre: "BORUSSIA DORTMUND",
        LocalSlug: "DORTMUND",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/Barcelona.webp",
        LocalNombre: "BARCELONA",
        LocalSlug: "BARCELONA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/bayern04.png",
        VisitanteNombre: "BAYERN 04 LEVERKUSEN",
        VisitanteSlug: "BAYERN 04",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/mancity.png",
        LocalNombre: "MANCHESTER CITY",
        LocalSlug: "MAN CITY",
        LocalResultado: 1,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalSlug: "REAL MADRID",
        LocalResultado: 0,
        VisitanteEscudo: "/images/bayern04.png",
        VisitanteNombre: "BAYERN 04 LEVERKUSEN",
        VisitanteSlug: "BAYERN 04",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/sevillaa.png",
        LocalNombre: "SEVILLA",
        LocalSlug: "SEVILLA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/BorussiaDortmund.png",
        LocalNombre: "BORUSSIA DORTMUND",
        LocalSlug: "DORTMUND",
        LocalResultado: 1,
        LocalPenalty: 6,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 1,
        VisitantePenalty: 7,
        Penalty: true,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MANCHESTER UNITED",
        LocalSlug: "MAN UNITED",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalSlug: "PORTO",
        LocalResultado: 1,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/newcastlee.png",
        LocalNombre: "NEWCASTLE",
        LocalSlug: "NEWCASTLE",
        LocalResultado: 3,
        VisitanteEscudo: "/images/valenciafc.png",
        VisitanteNombre: "VALENCIA",
        VisitanteSlug: "VALENCIA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalSlug: "TOTTENHAM",
        LocalResultado: 0,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteSlug: "REAL MADRID",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/mancity.png",
        LocalNombre: "MANCHESTER CITY",
        LocalSlug: "MAN CITY",
        LocalResultado: 1,
        VisitanteEscudo: "/images/oporto.png",
        VisitanteNombre: "PORTO",
        VisitanteSlug: "PORTO",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MANCHESTER UNITED",
        VisitanteSlug: "MAN UNITED",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 2,
        LocalPenalty: 3,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteSlug: "REAL MADRID",
        VisitanteResultado: 2,
        VisitantePenalty: 5,
        Penalty: true,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 1,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REALMADRID",
        VisitanteSlug: "REAL MADRID",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/milan_test.png",
        LocalNombre: "AC MILAN",
        LocalSlug: "AC MILAN",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 4,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteSlug: "LIVERPOOL",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalSlug: "ARSENAL",
        LocalResultado: 3,
        VisitanteEscudo: "/images/internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteSlug: "INTER",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "NO",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalSlug: "PORTO",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteSlug: "LIVERPOOL",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalSlug: "BAYERN",
        LocalResultado: 0,
        VisitanteEscudo: "/images/sevillaa.png",
        VisitanteNombre: "SEVILLA",
        VisitanteSlug: "SEVILLA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/SSC_Neapel.svg.png",
        LocalNombre: "NAPOLI",
        LocalSlug: "NAPOLI",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Zenit.png",
        VisitanteNombre: "ZENIT",
        VisitanteSlug: "ZENIT",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        LocalEscudo: "/images/ASRoma.png",
        LocalNombre: "ROMA",
        LocalSlug: "ROMA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MANCHESTER CITY",
        VisitanteSlug: "MAN CITY",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/AstonVilla.png",
        LocalNombre: "ASTON VILLA",
        LocalSlug: "ASTON VILLA",
        LocalResultado: 0,
        LocalPenalty: 5,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 0,
        VisitantePenalty: 4,
        Penalty: true,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        LocalEscudo: "/images/mancity.png",
        LocalNombre: "MANCHESTER CITY",
        LocalSlug: "MAN CITY",
        LocalResultado: 2,
        VisitanteEscudo: "/images/sevillaa.png",
        VisitanteNombre: "SEVILLA",
        VisitanteSlug: "SEVILLA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalSlug: "REAL MADRID",
        LocalResultado: 1,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteSlug: "BAYERN",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        isLegit: "L",
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalSlug: "REAL MADRID",
        LocalResultado: 3,
        VisitanteEscudo: "/images/internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteSlug: "INTER",
        VisitanteResultado: 0,
        Penalty: false,
      },
    ],
    stats: {
      win: 18,
      loss: 13,
      porcent: "59%",
    },
  },
  clasics: {
    matchs: [
      {
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        Raiz: "16Avos de Final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        Raiz: "Fase de grupos - Invierno",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        Raiz: "16avos de final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        LocalPenalty: 4,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        VisitantePenalty: 5,
        Penalty: true,
      },
      {
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "M",
        Result: "Victory",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        LocalPenalty: 5,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        VisitantePenalty: 4,
        Penalty: true,
      },
      {
        Player1: "G",
        Player2: "M",
        Result: "Draw",
        Raiz: "Amistoso",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "M",
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteSlug: "CHELSEA",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 2,
        LocalPenalty: 4,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 2,
        VisitantePenalty: 5,
        Penalty: true,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 3,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Cuartos de final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 2,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Draw",
        Raiz: "Fase de grupos - Verano",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Victory",
        Raiz: "16Avos",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 0,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Octavos de Final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 1,
        Penalty: false,
      },
      {
        Player1: "G",
        Player2: "F",
        Result: "Defeat",
        Raiz: "Cuartos de Final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalSlug: "JUVENTUS",
        LocalResultado: 0,
        LocalPenalty: 4,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteSlug: "PSG",
        VisitanteResultado: 0,
        VisitantePenalty: 5,
        Penalty: true,
      },
    ],
    stats: {
      win: 6,
      loss: 8,
      porcent: "41%",
    },
  },
};

export const stats_roma = {
  info: {
    photo_profile: "/images/gaston.jpg",
    background_profile: "/images/atleticomadrid_cover.webp",
    rank_profile: "25",
    shield_profile: "/images/AtleticoMadrid.png",
    background_blur_profile: "/images/atleticomadrid_cover.webp",
    photo_blur_profile: "/images/shield_blur.webp",
    name_profile: "Rodrigo",
    surname_profile: "Romero",
    team_id: "ATLETICO",
    team_profile: "MADRID",
    trophies: 0,
  },
  finals: {
    matchs: [ 
    ],
    stats: {
      win: 0,
      loss: 0,
      porcent: "0%",
    },
  },
  clasics: {
    matchs: [
    ],
    stats: {
      win: 0,
      loss: 0,
      porcent: "0%",
    },
  },
};


export const data = {
  poster: [
    {
      image: "/images/ajax_poster.webp",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image: "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY DESCIENDE",
      description: "Galatasaray desciende a la LIGA B.",
    },
    {
      image: "/images/inter_new.avif",
      alt: "poster_image",
      title: "INTER BICAMPEON",
      description:
        "Internazionale es BICAMPEON! derroto 2 - 1 a Everton FC, y 3 - 1 al Manchester City ",
    },
    {
      image: "/images/chelsea_poster.webp",
      alt: "poster_image",
      title: "¡CHELSEA CAMPEON!",
      description:
        "SE LE DIO, Chelsea es el nuevo campeon, vence la final por penales a Dortmund, de la mano de Marcos Aquino.",
    },
  ],
  new: [
    {
      image: "/images/poster_marcos.jpeg",
      alt: "poster_image",
      title: "¡CHELSEA CAMPEON!",
      description:
        "SE LE DIO, Chelsea es el nuevo campeon, vence la final por penales a Dortmund, de la mano de Marcos Aquino.",
    },
    {
      image: "/images/ajax_poster.webp",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image: "/images/porto_poster.webp",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description:
        "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
    },
    {
      image: "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
    },
    {
      image: "/images/alnassar_poster.webp",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
    },
    {
      image: "/images/ajax_poster.webp",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image: "/images/porto_poster.webp",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description:
        "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
    },
    {
      image: "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
    },
    {
      image: "/images/alnassar_poster.webp",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
    },
    {
      image: "/images/ajax_poster.webp",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image: "/images/porto_poster.webp",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description:
        "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
    },
    {
      image: "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
    },
    {
      image: "/images/alnassar_poster.webp",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
    },
  ],
  ranking: [
    {
      logo: "/images/ParisSaintGermain.png",
      cover: "/images/psg_cover.webp",
      rank: 1,
      name: "PARIS SAINT GERMAIN",
      titles: 6,
    },
    {
      logo: "/images/BayernMunchen.png",
      cover: "/images/bayernmunich_cover.avif",
      rank: 2,
      name: "BAYERN MUNICH",
      titles: 5,
    },
    {
      logo: "/images/mancity.png",
      cover: "/images/manchestercity_cover.webp",
      rank: 3,
      name: "MANCHESTER CITY",
      titles: 4,
    },
    {
      logo: "/images/ManchesterUnited.png",
      cover: "/images/manchesterunited_cover.webp",
      rank: 4,
      name: "MANCHESTER UNITED",
      titles: 3,
    },
    {
      logo: "/images/RealMadrid.png",
      cover: "/images/realmadrid_cover.webp",
      rank: 5,
      name: "REAL MADRID",
      titles: 3,
    },
    {
      logo: "/images/Internazionale.png",
      cover: "/images/inter_cover.webp",
      rank: 6,
      name: "INTER",
      titles: 3,
    },
    {
      logo: "/images/Barcelona.webp",
      cover: "/images/barcelona_cover.webp",
      rank: 7,
      name: "BARCELONA",
      titles: 3,
    },
    {
      logo: "/images/Tottenham.png",
      cover: "/images/tottenham_cover.webp",
      rank: 8,
      name: "TOTTENHAM",
      titles: 2,
    },
    {
      logo: "/images/newcastlee.png",
      cover: "/images/newcastle_cover.webp",
      rank: 9,
      name: "NEWCASTLE",
      titles: 2,
    },
    {
      logo: "/images/oporto.png",
      cover: "/images/porto_cover.webp",
      rank: 10,
      name: "PORTO",
      titles: 2,
    },
    {
      logo: "/images/Chelsea.png",
      cover: "/images/chelsea_cover.webp",
      rank: 11,
      name: "CHELSEA",
      titles: 2,
    },
    {
      logo: "/images/sevillaa.png",
      cover: "/images/sevilla_cover.avif",
      rank: 12,
      name: "SEVILLA",
      titles: 2,
    },
    {
      logo: "/images/arsenalfc.png",
      cover: "/images/arsenal_cover.webp",
      rank: 13,
      name: "ARSENAL",
      titles: 2,
    },
    {
      logo: "/images/Liverpool.png",
      cover: "/images/liverpool_cover.webp",
      rank: 14,
      name: "LIVERPOOL",
      titles: 2,
    },
    {
      logo: "/images/AstonVilla.png",
      cover: "/images/astonvilla_cover.webp",
      rank: 15,
      name: "ASTON VILLA",
      titles: 1,
    },
    {
      logo: "/images/SSC_Neapel.svg.png",
      cover: "/images/napoli_cover.webp",
      rank: 16,
      name: "NAPOLI",
      titles: 1,
    },
    {
      logo: "/images/valenciafc.png",
      cover: "/images/valencia_cover.webp",
      rank: 17,
      name: "VALENCIA",
      titles: 1,
    },

    {
      logo: "/images/da-removebg-preview.png",
      cover: "/images/juventus_cover.webp",
      rank: 18,
      name: "JUVENTUS",
      titles: 1,
    },
    {
      logo: "/images/villar.png",
      cover: "/images/villareal_cover.webp",
      rank: 19,
      name: "VILLA REAL",
      titles: 1,
    },

    {
      logo: "/images/Ajax.png",
      cover: "/images/ajax_cover.avif",
      rank: 20,
      name: "AJAX",
      titles: 1,
    },
    {
      logo: "/images/bayern04.png",
      cover: "/images/bayern04_cover.webp",
      rank: 21,
      name: "BAYERN 04 LEVERKUSEN",
      titles: 1,
    },
    {
      logo: "/images/BorussiaDortmund.png",
      cover: "/images/dortmund_cover.avif",
      rank: 22,
      name: "BORUSSIA DORTMUND",
      titles: 1,
    },
    {
      logo: "/images/Zenit.png",
      cover: "/images/zenit_cover.webp",
      rank: 23,
      name: "ZENIT",
      titles: 0,
    },

    {
      logo: "/images/milan_test.png",
      cover: "/images/milan_cover.webp",
      rank: 24,
      name: "AC MILAN",
      titles: 0,
    },
    {
      logo: "/images/AtleticoMadrid.png",
      cover: "/images/atleticomadrid_cover.webp",
      rank: 25,
      name: "ATLETICO MADRID",
      titles: 0,
    },
    {
      logo: "/images/laziofc.png",
      cover: "/images/lazio_cover.webp",
      rank: 26,
      name: "LAZIO",
      titles: 0,
    },
    {
      logo: "/images/Benfica.png",
      cover: "/images/benfica_cover.webp",
      rank: 27,
      name: "BENFICA",
      titles: 0,
    },
    {
      logo: "/images/SportingLisboa.png",
      cover: "/images/sporting_cover.webp",
      rank: 28,
      name: "SPORTING LISBOA",
      titles: 0,
    },

    {
      logo: "/images/evertonfc.png",
      cover: "/images/everton_cover.webp",
      rank: 29,
      name: "EVERTON",
      titles: 0,
    },
    {
      logo: "/images/ASRoma.png",
      cover: "/images/roma_cover.webp",
      rank: 30,
      name: "AS ROMA",
      titles: 0,
    },

    {
      logo: "/images/wolfburgo.png",
      cover: "/images/wolfburgo_cover.webp",
      rank: 31,
      name: "WOLFSBURGO",
      titles: 0,
    },
    {
      logo: "/images/Lyon.png",
      cover: "/images/lyon_cover.webp",
      rank: 32,
      name: "OLYMPIQUE LYON",
      titles: 0,
    },

    {
      logo: "/images/galatasaray.png",
      cover: "/images/bakcground_rank.webp",
      rank: 33,
      name: "GALATASARAY",
      titles: 0,
    },
    {
      logo: "/images/fiorentina.png",
      cover: "/images/bakcground_rank.webp",
      rank: 40,
      name: "FIORENTINA",
      titles: 0,
    },
    {
      logo: "/images/realsociedad.png",
      cover: "/images/bakcground_rank.webp",
      rank: 34,
      name: "REAL SOCIEDAD",
      titles: 0,
    },
    {
      logo: "/images/BOCA.png",
      cover: "/images/bakcground_rank.webp",
      rank: 35,
      name: "BOCA JUNIORS",
      titles: 0,
    },
    {
      logo: "/images/river.png",
      cover: "/images/bakcground_rank.webp",
      rank: 36,
      name: "RIVER PLATE",
      titles: 0,
    },
    {
      logo: "/images/flam.png",
      cover: "/images/bakcground_rank.webp",
      rank: 37,
      name: "FLAMENGO",
      titles: 0,
    },
    {
      logo: "/images/slo.png",
      cover: "/images/bakcground_rank.webp",
      rank: 38,
      name: "SAN LORENZO",
      titles: 0,
    },
  ],
};

export const top20 = {
  players: [
    {
      rank: 1,
      name: "Zlatan Ibramovic",
      team: "Paris Saint Germain",
      image: "/images/ibramovic.webp",
    },
    {
      rank: 2,
      name: "Arjen Robben",
      team: "Bayern Munich",
      image: "/images/robben.webp",
    },
    {
      rank: 3,
      name: "Dante Bonfim",
      team: "Bayern Munich",
      image: "/images/dante.webp",
    },
    {
      rank: 4,
      name: "Sergio Ramos",
      team: "Real Madrid",
      image: "/images/ramos.webp",
    },
    {
      rank: 5,
      name: "Robin van Persie",
      team: "Manchester United",
      image: "/images/van persie.webp",
    },
    {
      rank: 6,
      name: "Erling Haaland",
      team: "Manchester City",
      image: "/images/haaland.webp",
    },
    {
      rank: 7,
      name: "Manuel Neuer",
      team: "Bayern Munich",
      image: "/images/never.webp",
    },
    {
      rank: 8,
      name: "Blaise Matuidi",
      team: "Paris Saint Germain",
      image: "/images/matuidi.webp",
    },
    {
      rank: 9,
      name: "Kun Agüero",
      team: "Manchester City",
      image: "/images/aguero.webp",
    },
    {
      rank: 10,
      name: "Thomas Müller",
      team: "Bayern Munich",
      image: "/images/muller.webp",
    },
    {
      rank: 11,
      name: "Victor Osimhen",
      team: "Barcelona",
      image: "/images/oshimen.webp",
    },
    {
      rank: 12,
      name: "Carlos Tévez",
      team: "Juventus",
      image: "/images/tevez.webp",
    },
    {
      rank: 13,
      name: "Thibaut Courtois",
      team: "Chelsea",
      image: "/images/courtois.webp",
    },
    {
      rank: 14,
      name: "Edinson Cavani",
      team: "Paris Saint Germain",
      image: "/images/cavani.webp",
    },
    {
      rank: 15,
      name: "Neymar",
      team: "Barcelona",
      image: "/images/neymar.webp",
    },
    {
      rank: 16,
      name: "Gerard Piqué",
      team: "Barcelona",
      image: "/images/pique.webp",
    },
    {
      rank: 17,
      name: "Gareth Bale",
      team: "Real Madrid",
      image: "/images/bale.webp",
    },
    {
      rank: 18,
      name: "Jackson Martínez",
      team: "Porto",
      image: "/images/jackson.webp",
    },
    {
      rank: 19,
      name: "Eden Hazard",
      team: "Chelsea",
      image: "/images/hazard.webp",
    },
    {
      rank: 20,
      name: "Ramires",
      team: "Newcastle",
      image: "/images/ramires.webp",
    },
  ],
};


export const usuarios =  
  [
    {
      "id": 1,
      "created_at": "2025-04-01T13:24:36.789562+00:00",
      "email": "francoo_chaparro@hotmail.co",
      "nombre": "franco chaparro"
    },
    {
      "id": 2,
      "created_at": "2025-04-01T13:25:05.151155+00:00",
      "email": "garbandev@gmail.com",
      "nombre": "pablo garban"
    },
    {
      "id": 3,
      "created_at": "2025-04-01T13:25:23.814073+00:00",
      "email": "tomas@gmail.com",
      "nombre": "tomas dibacco"
    }
  ]
